import Foundation
import Testing
@testable import Clawd

/// Builders for Claude Code transcript lines (~/.claude/projects/<dir>/<session>.jsonl).
enum Entry {
    static func line(_ object: [String: Any]) -> String {
        let data = try! JSONSerialization.data(withJSONObject: object, options: [.sortedKeys])
        return String(decoding: data, as: UTF8.self) + "\n"
    }

    static func user(_ uuid: String, _ content: Any, extra: [String: Any] = [:]) -> String {
        line(["type": "user", "uuid": uuid, "sessionId": "s1", "isSidechain": false,
              "message": ["role": "user", "content": content]].merging(extra) { $1 })
    }

    static func assistant(_ uuid: String, _ blocks: [[String: Any]], extra: [String: Any] = [:]) -> String {
        line(["type": "assistant", "uuid": uuid, "sessionId": "s1", "isSidechain": false,
              "message": ["role": "assistant", "model": "claude-opus-5-5", "content": blocks]].merging(extra) { $1 })
    }

    static func text(_ s: String) -> [String: Any] { ["type": "text", "text": s] }
    static func thinking(_ s: String) -> [String: Any] { ["type": "thinking", "thinking": s, "signature": "sig"] }
    static func toolUse(_ id: String, _ name: String, _ input: [String: Any]) -> [String: Any] {
        ["type": "tool_use", "id": id, "name": name, "input": input]
    }
    static func toolResult(_ id: String, _ content: Any, error: Bool = false) -> [String: Any] {
        ["type": "tool_result", "tool_use_id": id, "content": content, "is_error": error]
    }
}

/// A transcript file in its own temporary folder. Tests remove it with `defer { file.remove() }`;
/// a deinit could run before the reader's last read, since Swift may end a lifetime at last use.
final class TempTranscript {
    let dir: URL
    let url: URL

    init() throws {
        dir = FileManager.default.temporaryDirectory.appendingPathComponent("clawd-tests-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        url = dir.appendingPathComponent("session.jsonl")
        FileManager.default.createFile(atPath: url.path, contents: nil)
    }

    func remove() { try? FileManager.default.removeItem(at: dir) }

    func append(_ text: String) throws {
        let handle = try FileHandle(forWritingTo: url)
        defer { try? handle.close() }
        try handle.seekToEnd()
        try handle.write(contentsOf: Data(text.utf8))
    }

    /// Writes a new file and moves it over the old one, as an editor or `cp` would (new inode).
    func replace(with text: String) throws {
        try Data(text.utf8).write(to: url, options: .atomic)
    }

    func truncate(to length: UInt64) throws {
        let handle = try FileHandle(forWritingTo: url)
        defer { try? handle.close() }
        try handle.truncate(atOffset: length)
    }
}

/// A short session: an older turn, injected entries, then the current turn with tool calls.
let sessionLines: [String] = [
    Entry.line(["type": "summary", "summary": "Earlier work", "leafUuid": "x"]),
    Entry.user("u0", "Add a README"),
    Entry.assistant("a0", [Entry.text("Added README.md.")]),
    // A slash-command echo and an isMeta caveat are not prompts and must not start a turn.
    Entry.user("c1", "<command-name>/model</command-name>\n<command-message>model</command-message>\n<command-args></command-args>"),
    Entry.user("m1", "Caveat: the messages below were generated by the user", extra: ["isMeta": true]),
    Entry.user("u1", [Entry.text("Run the tests and fix failures")]),
    Entry.assistant("a1", [Entry.thinking(""), Entry.thinking("Plan: run npm test first."), Entry.text("I'll run the suite.")]),
    Entry.assistant("a2", [Entry.toolUse("toolu_1", "Bash", ["command": "npm test", "description": "Run unit tests"])]),
    // A subagent's entries live in the same file but are not part of the main conversation.
    Entry.assistant("s1", [Entry.text("subagent chatter")], extra: ["isSidechain": true]),
    Entry.user("r1", [Entry.toolResult("toolu_1", "3 passing\n  1 failing", error: true)]),
    Entry.assistant("a3", [Entry.toolUse("toolu_2", "Read", ["file_path": "/repo/Sources/Parser.swift"])]),
    Entry.user("i1", [Entry.text("[Request interrupted by user]")]),
    // Claude Code sometimes writes an entry twice; the duplicate must not add an item.
    Entry.assistant("a3", [Entry.toolUse("toolu_2", "Read", ["file_path": "/repo/Sources/Parser.swift"])]),
]

@Suite(.serialized) struct TranscriptReaderTests {
    func expectCurrentTurn(_ items: [TimelineItem], readResult: String?) {
        #expect(items.map(\.id) == ["u1:u", "a1:0", "a1:2", "toolu_1", "toolu_2"])
        #expect(items[0] == TimelineItem(id: "u1:u", kind: .user, text: "Run the tests and fix failures"))
        #expect(items[1] == TimelineItem(id: "a1:0", kind: .thinking, text: "Plan: run npm test first."))
        #expect(items[2] == TimelineItem(id: "a1:2", kind: .text, text: "I'll run the suite."))
        #expect(items[3].kind == .tool(name: "Bash", result: "3 passing 1 failing", failed: true))
        #expect(items[3].text == "Run unit tests")
        #expect(items[4].text == "Parser.swift")
        if let readResult {
            #expect(items[4].kind == .tool(name: "Read", result: readResult, failed: false))
        } else {
            #expect(items[4].kind == .tool(name: "Read", result: nil, failed: false))
        }
    }

    @Test func buildsTimelineOfLatestTurn() throws {
        let file = try TempTranscript()
        defer { file.remove() }
        try file.append(sessionLines.joined())
        let reader = TranscriptReader(url: file.url)
        let (items, changed) = reader.timeline()
        #expect(changed)
        expectCurrentTurn(items, readResult: nil)
    }

    @Test func followsAppendedLinesAndWaitsForPartialOnes() throws {
        let file = try TempTranscript()
        defer { file.remove() }
        try file.append(sessionLines.joined())
        let reader = TranscriptReader(url: file.url)
        _ = reader.timeline()

        // Nothing new: same items, not changed.
        let idle = reader.timeline()
        #expect(!idle.changed)
        expectCurrentTurn(idle.items, readResult: nil)

        // The Read result arrives, followed by half of the next assistant line.
        let next = Entry.assistant("a4", [Entry.text("Fixed the off-by-one in Parser.swift.")])
        let cut = next.index(next.startIndex, offsetBy: next.count / 2)
        try file.append(Entry.user("r2", [Entry.toolResult("toolu_2", [["type": "text", "text": "struct Parser {"]])])
                        + String(next[..<cut]))
        let partial = reader.timeline()
        #expect(partial.changed)
        expectCurrentTurn(partial.items, readResult: "struct Parser {")

        #expect(!reader.timeline().changed)

        // The rest of the line lands; only now is it read, and in full.
        try file.append(String(next[cut...]))
        let complete = reader.timeline()
        #expect(complete.changed)
        #expect(complete.items.count == 6)
        #expect(complete.items.last == TimelineItem(id: "a4:0", kind: .text, text: "Fixed the off-by-one in Parser.swift."))

        // An incremental read agrees with a fresh one over the same bytes.
        #expect(TranscriptReader(url: file.url).timeline().items == complete.items)
    }

    @Test func newPromptStartsANewTurn() throws {
        let file = try TempTranscript()
        defer { file.remove() }
        try file.append(sessionLines.joined())
        let reader = TranscriptReader(url: file.url)
        _ = reader.timeline()
        try file.append(Entry.user("u2", "Now update the changelog") + Entry.assistant("a5", [Entry.text("Done.")]))
        let items = reader.timeline().items
        #expect(items.map(\.id) == ["u2:u", "a5:0"])
    }

    @Test func toolResultForAnEarlierTurnIsIgnored() throws {
        let file = try TempTranscript()
        defer { file.remove() }
        try file.append(sessionLines.joined() + Entry.user("u2", "Next task"))
        let reader = TranscriptReader(url: file.url)
        _ = reader.timeline()
        try file.append(Entry.user("r9", [Entry.toolResult("toolu_2", "late result")]))
        let (items, changed) = reader.timeline()
        #expect(items.map(\.id) == ["u2:u"])
        #expect(!changed)
    }

    @Test func resetsWhenTruncated() throws {
        let file = try TempTranscript()
        defer { file.remove() }
        let firstTurn = sessionLines[0...2].joined()
        try file.append(sessionLines.joined())
        let reader = TranscriptReader(url: file.url)
        _ = reader.timeline()

        try file.truncate(to: UInt64(firstTurn.utf8.count))
        let (items, changed) = reader.timeline()
        #expect(changed)
        #expect(items.map(\.id) == ["u0:u", "a0:0"])
    }

    @Test func resetsWhenReplaced() throws {
        let file = try TempTranscript()
        defer { file.remove() }
        try file.append(sessionLines.joined())
        let reader = TranscriptReader(url: file.url)
        _ = reader.timeline()

        // A different file of the same or larger size at the same path: a new inode.
        let other = Entry.user("v1", "Other session prompt") + Entry.assistant("b1", [Entry.text(String(repeating: "x", count: 4000))])
        try file.replace(with: other)
        let (items, changed) = reader.timeline()
        #expect(changed)
        #expect(items.map(\.id) == ["v1:u", "b1:0"])
    }

    @Test func missingFileGivesEmptyTimeline() throws {
        let file = try TempTranscript()
        defer { file.remove() }
        try file.append(sessionLines.joined())
        let reader = TranscriptReader(url: file.url)
        #expect(!reader.timeline().items.isEmpty)
        try FileManager.default.removeItem(at: file.url)
        let gone = reader.timeline()
        #expect(gone.items.isEmpty)
        #expect(gone.changed)
    }

    @Test func entriesWithoutUUIDGetPositionalIds() throws {
        let file = try TempTranscript()
        defer { file.remove() }
        try file.append(Entry.line(["type": "user", "message": ["role": "user", "content": "hi"]])
                        + Entry.line(["type": "assistant", "message": ["content": [Entry.text("hello")]]]))
        let items = TranscriptReader(url: file.url).timeline().items
        #expect(items.map(\.id) == ["p1.u", "p2.0"])
    }

    @Test func cachedReaderIsSharedPerPath() throws {
        let file = try TempTranscript()
        defer { file.remove() }
        try file.append(sessionLines.joined())
        let reader = Transcripts.reader(for: file.url)
        let dotted = file.dir.appendingPathComponent("./session.jsonl")
        #expect(Transcripts.reader(for: dotted) === reader)
        expectCurrentTurn(Transcripts.timeline(file.url), readResult: nil)
        // The shared reader has consumed the file, so asking again reports no change.
        #expect(!reader.timeline().changed)
    }
}

@Suite struct TranscriptHelpersTests {
    @Test func promptTextStripsInjectedTags() {
        func entry(_ content: Any, meta: Bool = false) -> [String: Any] {
            ["type": "user", "isMeta": meta, "message": ["content": content]]
        }
        #expect(Transcripts.promptText(entry("Fix it")) == "Fix it")
        #expect(Transcripts.promptText(entry("<system-reminder>be nice</system-reminder>\nFix it")) == "Fix it")
        #expect(Transcripts.promptText(entry("<bash-input>ls</bash-input>")) == nil)
        #expect(Transcripts.promptText(entry("Fix it", meta: true)) == nil)
        #expect(Transcripts.promptText(entry("[Request interrupted by user for tool use]")) == nil)
        #expect(Transcripts.promptText(entry([Entry.text("a"), Entry.text("b")])) == "a\nb")
        #expect(Transcripts.promptText(entry([Entry.toolResult("t", "out")])) == nil)
        #expect(Transcripts.promptText(["type": "assistant", "message": ["content": "x"]]) == nil)
    }

    @Test func toolSummaries() {
        #expect(Transcripts.summary("Bash", ["command": "ls -la"]) == "ls -la")
        #expect(Transcripts.summary("Bash", ["command": "ls -la", "description": "List files"]) == "List files")
        #expect(Transcripts.summary("Edit", ["file_path": "/a/b/c.swift", "old_string": "x"]) == "c.swift")
        #expect(Transcripts.summary("Grep", ["pattern": "TODO"]) == "TODO")
        #expect(Transcripts.summary("TodoWrite", ["todos": []]) == "Update to-do list")
        #expect(Transcripts.summary("mcp__x__y", ["zeta": "z", "alpha": "a"]) == "a")
        #expect(Transcripts.summary("mcp__x__y", ["zeta": "z", "url": "https://e.com"]) == "https://e.com")
        #expect(Transcripts.summary("Unknown", [:]) == "")
    }

    @Test func claudeHomeFollowsConfigDir() {
        let home = FileManager.default.homeDirectoryForCurrentUser
        #expect(Transcripts.claudeHome([:]).path == home.appendingPathComponent(".claude").path)
        #expect(Transcripts.claudeHome(["CLAUDE_CONFIG_DIR": ""]).path == home.appendingPathComponent(".claude").path)
        #expect(Transcripts.claudeHome(["CLAUDE_CONFIG_DIR": "/work/claude"]).path == "/work/claude")
        #expect(Transcripts.claudeHome(["CLAUDE_CONFIG_DIR": "~/alt"]).path == home.appendingPathComponent("alt").path)
    }

    @Test func resultText() {
        #expect(Transcripts.resultText("a\n\nb") == "a b")
        #expect(Transcripts.resultText([["type": "text", "text": "one"], ["type": "image"], ["type": "text", "text": "two"]]) == "one two")
        #expect(Transcripts.resultText(nil) == nil)
    }
}
