using System.Text.Json.Nodes;
using Clawd.Core.Transcripts;

namespace Clawd.Core.Tests;

/// <summary>Builders for Claude Code transcript lines (~/.claude/projects/&lt;dir&gt;/&lt;session&gt;.jsonl).</summary>
internal static class Entry
{
    // Raw UTF-8, as Claude Code writes it, not \uXXXX escapes.
    private static readonly System.Text.Json.JsonSerializerOptions Raw = new() { Encoder = System.Text.Encodings.Web.JavaScriptEncoder.UnsafeRelaxedJsonEscaping };

    public static string Line(JsonObject o) => o.ToJsonString(Raw) + "\n";

    private static JsonObject Merge(JsonObject o, JsonObject? extra)
    {
        foreach (var (k, v) in extra ?? []) o[k] = v?.DeepClone();
        return o;
    }

    public static string User(string uuid, JsonNode content, JsonObject? extra = null) => Line(Merge(new JsonObject
    {
        ["type"] = "user", ["uuid"] = uuid, ["sessionId"] = "s1", ["isSidechain"] = false,
        ["message"] = new JsonObject { ["role"] = "user", ["content"] = content },
    }, extra));

    public static string Assistant(string uuid, JsonArray blocks, JsonObject? extra = null) => Line(Merge(new JsonObject
    {
        ["type"] = "assistant", ["uuid"] = uuid, ["sessionId"] = "s1", ["isSidechain"] = false,
        ["message"] = new JsonObject { ["role"] = "assistant", ["model"] = "claude-opus-5-5", ["content"] = blocks },
    }, extra));

    public static JsonObject Text(string s) => new() { ["type"] = "text", ["text"] = s };
    public static JsonObject Thinking(string s) => new() { ["type"] = "thinking", ["thinking"] = s, ["signature"] = "sig" };
    public static JsonObject ToolUse(string id, string name, JsonObject input) => new() { ["type"] = "tool_use", ["id"] = id, ["name"] = name, ["input"] = input };
    public static JsonObject ToolResult(string id, JsonNode content, bool error = false) =>
        new() { ["type"] = "tool_result", ["tool_use_id"] = id, ["content"] = content, ["is_error"] = error };
}

/// <summary>A transcript file in its own temporary folder, removed on dispose.</summary>
internal sealed class TempTranscript : IDisposable
{
    public string Dir { get; } = Directory.CreateTempSubdirectory("clawd-tests-").FullName;
    public string Path => System.IO.Path.Combine(Dir, "session.jsonl");

    public TempTranscript() => File.WriteAllText(Path, "");

    public void Append(string text)
    {
        // Shared like Claude Code's own writes, so a reader holding the file open never blocks it.
        using var s = new FileStream(Path, FileMode.Append, FileAccess.Write, FileShare.ReadWrite | FileShare.Delete);
        var bytes = System.Text.Encoding.UTF8.GetBytes(text);
        s.Write(bytes);
    }

    /// <summary>Writes a new file and moves it over the old one, as an editor or `cp` would (new file ID).</summary>
    public void Replace(string text)
    {
        var temp = Path + ".new";
        File.WriteAllText(temp, text);
        File.Move(temp, Path, overwrite: true);
    }

    public void Truncate(long length)
    {
        using var s = new FileStream(Path, FileMode.Open, FileAccess.Write, FileShare.ReadWrite | FileShare.Delete);
        s.SetLength(length);
    }

    public void Dispose()
    {
        try { Directory.Delete(Dir, true); } catch (IOException) { }
    }
}

public class TranscriptReaderTests
{
    /// <summary>A short session: an older turn, injected entries, then the current turn with tool calls.</summary>
    internal static readonly string[] SessionLines =
    [
        Entry.Line(new JsonObject { ["type"] = "summary", ["summary"] = "Earlier work", ["leafUuid"] = "x" }),
        Entry.User("u0", "Add a README"),
        Entry.Assistant("a0", [Entry.Text("Added README.md.")]),
        // A slash-command echo and an isMeta caveat are not prompts and must not start a turn.
        Entry.User("c1", "<command-name>/model</command-name>\n<command-message>model</command-message>\n<command-args></command-args>"),
        Entry.User("m1", "Caveat: the messages below were generated by the user", new JsonObject { ["isMeta"] = true }),
        Entry.User("u1", new JsonArray(Entry.Text("Run the tests and fix failures"))),
        Entry.Assistant("a1", [Entry.Thinking(""), Entry.Thinking("Plan: run npm test first."), Entry.Text("I'll run the suite.")]),
        Entry.Assistant("a2", [Entry.ToolUse("toolu_1", "Bash", new JsonObject { ["command"] = "npm test", ["description"] = "Run unit tests" })]),
        // A subagent's entries live in the same file but are not part of the main conversation.
        Entry.Assistant("s1", [Entry.Text("subagent chatter")], new JsonObject { ["isSidechain"] = true }),
        Entry.User("r1", new JsonArray(Entry.ToolResult("toolu_1", "3 passing\n  1 failing", error: true))),
        Entry.Assistant("a3", [Entry.ToolUse("toolu_2", "Read", new JsonObject { ["file_path"] = @"C:\repo\Sources\Parser.cs" })]),
        Entry.User("i1", new JsonArray(Entry.Text("[Request interrupted by user]"))),
        // Claude Code sometimes writes an entry twice; the duplicate must not add an item.
        Entry.Assistant("a3", [Entry.ToolUse("toolu_2", "Read", new JsonObject { ["file_path"] = @"C:\repo\Sources\Parser.cs" })]),
    ];

    private static void ExpectCurrentTurn(IReadOnlyList<TimelineItem> items, string? readResult)
    {
        Assert.Equal(["u1:u", "a1:0", "a1:2", "toolu_1", "toolu_2"], items.Select(i => i.Id));
        Assert.Equal(new TimelineItem("u1:u", TimelineKind.User, "Run the tests and fix failures"), items[0]);
        Assert.Equal(new TimelineItem("a1:0", TimelineKind.Thinking, "Plan: run npm test first."), items[1]);
        Assert.Equal(new TimelineItem("a1:2", TimelineKind.Text, "I'll run the suite."), items[2]);
        Assert.Equal(TimelineItem.Tool("toolu_1", "Bash", "Run unit tests", "3 passing 1 failing", true), items[3]);
        Assert.Equal(TimelineItem.Tool("toolu_2", "Read", "Parser.cs", readResult), items[4]);
    }

    [Fact]
    public void BuildsTimelineOfLatestTurn()
    {
        using var file = new TempTranscript();
        file.Append(string.Concat(SessionLines));
        var (items, changed) = new TranscriptReader(file.Path).Timeline();
        Assert.True(changed);
        ExpectCurrentTurn(items, null);
    }

    [Fact]
    public void FollowsAppendedLinesAndWaitsForPartialOnes()
    {
        using var file = new TempTranscript();
        file.Append(string.Concat(SessionLines));
        var reader = new TranscriptReader(file.Path);
        reader.Timeline();

        // Nothing new: same items, not changed.
        var idle = reader.Timeline();
        Assert.False(idle.Changed);
        ExpectCurrentTurn(idle.Items, null);

        // The Read result arrives, followed by half of the next assistant line.
        var next = Entry.Assistant("a4", [Entry.Text("Fixed the off-by-one in Parser.cs.")]);
        var cut = next.Length / 2;
        file.Append(Entry.User("r2", new JsonArray(Entry.ToolResult("toolu_2", new JsonArray(new JsonObject { ["type"] = "text", ["text"] = "class Parser {" })))) + next[..cut]);
        var partial = reader.Timeline();
        Assert.True(partial.Changed);
        ExpectCurrentTurn(partial.Items, "class Parser {");

        Assert.False(reader.Timeline().Changed);

        // The rest of the line lands; only now is it read, and in full.
        file.Append(next[cut..]);
        var complete = reader.Timeline();
        Assert.True(complete.Changed);
        Assert.Equal(6, complete.Items.Count);
        Assert.Equal(new TimelineItem("a4:0", TimelineKind.Text, "Fixed the off-by-one in Parser.cs."), complete.Items[^1]);

        // An incremental read agrees with a fresh one over the same bytes.
        Assert.Equal(complete.Items, new TranscriptReader(file.Path).Timeline().Items);
    }

    [Fact]
    public void LinesSplitInsideAMultibyteCharacterStillParse()
    {
        using var file = new TempTranscript();
        var line = Entry.Assistant("k1", [Entry.Text("한글 답장이에요")]);
        var bytes = System.Text.Encoding.UTF8.GetBytes(line);
        var cut = System.Text.Encoding.UTF8.GetByteCount(line[..line.IndexOf('글')]) + 1;   // inside "글"
        File.WriteAllBytes(file.Path, bytes[..cut]);
        var reader = new TranscriptReader(file.Path);
        Assert.Empty(reader.Timeline().Items);
        using (var s = new FileStream(file.Path, FileMode.Append)) s.Write(bytes[cut..]);
        Assert.Equal("한글 답장이에요", reader.Timeline().Items.Single().Text);
    }

    [Fact]
    public void NewPromptStartsANewTurn()
    {
        using var file = new TempTranscript();
        file.Append(string.Concat(SessionLines));
        var reader = new TranscriptReader(file.Path);
        reader.Timeline();
        file.Append(Entry.User("u2", "Now update the changelog") + Entry.Assistant("a5", [Entry.Text("Done.")]));
        Assert.Equal(["u2:u", "a5:0"], reader.Timeline().Items.Select(i => i.Id));
    }

    [Fact]
    public void ToolResultForAnEarlierTurnIsIgnored()
    {
        using var file = new TempTranscript();
        file.Append(string.Concat(SessionLines) + Entry.User("u2", "Next task"));
        var reader = new TranscriptReader(file.Path);
        reader.Timeline();
        file.Append(Entry.User("r9", new JsonArray(Entry.ToolResult("toolu_2", "late result"))));
        var (items, changed) = reader.Timeline();
        Assert.Equal(["u2:u"], items.Select(i => i.Id));
        Assert.False(changed);
    }

    [Fact]
    public void ResetsWhenTruncated()
    {
        using var file = new TempTranscript();
        var firstTurn = string.Concat(SessionLines[..3]);
        file.Append(string.Concat(SessionLines));
        var reader = new TranscriptReader(file.Path);
        reader.Timeline();

        file.Truncate(System.Text.Encoding.UTF8.GetByteCount(firstTurn));
        var (items, changed) = reader.Timeline();
        Assert.True(changed);
        Assert.Equal(["u0:u", "a0:0"], items.Select(i => i.Id));
    }

    [Fact]
    public void ResetsWhenReplaced()
    {
        using var file = new TempTranscript();
        file.Append(string.Concat(SessionLines));
        var reader = new TranscriptReader(file.Path);
        reader.Timeline();

        // A different file of the same or larger size at the same path.
        file.Replace(Entry.User("v1", "Other session prompt") + Entry.Assistant("b1", [Entry.Text(new string('x', 4000))]));
        var (items, changed) = reader.Timeline();
        Assert.True(changed);
        Assert.Equal(["v1:u", "b1:0"], items.Select(i => i.Id));
    }

    [Fact]
    public void MissingFileGivesEmptyTimeline()
    {
        using var file = new TempTranscript();
        file.Append(string.Concat(SessionLines));
        var reader = new TranscriptReader(file.Path);
        Assert.NotEmpty(reader.Timeline().Items);
        File.Delete(file.Path);
        var gone = reader.Timeline();
        Assert.Empty(gone.Items);
        Assert.True(gone.Changed);
    }

    [Fact]
    public void EntriesWithoutUuidGetPositionalIds()
    {
        using var file = new TempTranscript();
        file.Append(Entry.Line(new JsonObject { ["type"] = "user", ["message"] = new JsonObject { ["role"] = "user", ["content"] = "hi" } })
            + Entry.Line(new JsonObject { ["type"] = "assistant", ["message"] = new JsonObject { ["content"] = new JsonArray(Entry.Text("hello")) } }));
        Assert.Equal(["p1.u", "p2.0"], new TranscriptReader(file.Path).Timeline().Items.Select(i => i.Id));
    }

    [Fact]
    public void LongTurnKeepsTheNewestEightyAndStillMatchesResults()
    {
        using var file = new TempTranscript();
        var text = Entry.User("u", "go");
        for (var i = 0; i < 300; i++) text += Entry.Assistant($"a{i}", [Entry.ToolUse($"t{i}", "Bash", new JsonObject { ["command"] = $"step {i}" })]);
        file.Append(text);
        var reader = new TranscriptReader(file.Path);
        var items = reader.Timeline().Items;
        Assert.Equal(80, items.Count);
        Assert.Equal("t299", items[^1].Id);
        file.Append(Entry.User("r", new JsonArray(Entry.ToolResult("t299", "ok"))));
        Assert.Equal("ok", reader.Timeline().Items[^1].Result);
    }

    [Fact]
    public void CachedReaderIsSharedPerPath()
    {
        using var file = new TempTranscript();
        file.Append(string.Concat(SessionLines));
        var reader = Transcripts.Transcripts.Reader(file.Path);
        var dotted = Path.Combine(file.Dir, ".", "session.jsonl");
        Assert.Same(reader, Transcripts.Transcripts.Reader(dotted));
        ExpectCurrentTurn(Transcripts.Transcripts.Timeline(file.Path), null);
        // The shared reader has consumed the file, so asking again reports no change.
        Assert.False(reader.Timeline().Changed);
    }
}

[UseCulture("ko-KR")]
public class TranscriptHelpersTests
{
    private static JsonObject UserEntry(JsonNode content, bool meta = false) =>
        new() { ["type"] = "user", ["isMeta"] = meta, ["message"] = new JsonObject { ["content"] = content } };

    [Fact]
    public void PromptTextStripsInjectedTags()
    {
        Assert.Equal("Fix it", Transcripts.Transcripts.PromptText(UserEntry("Fix it")));
        Assert.Equal("Fix it", Transcripts.Transcripts.PromptText(UserEntry("<system-reminder>be nice</system-reminder>\nFix it")));
        Assert.Null(Transcripts.Transcripts.PromptText(UserEntry("<bash-input>ls</bash-input>")));
        Assert.Null(Transcripts.Transcripts.PromptText(UserEntry("Fix it", meta: true)));
        Assert.Null(Transcripts.Transcripts.PromptText(UserEntry("[Request interrupted by user for tool use]")));
        Assert.Equal("a\nb", Transcripts.Transcripts.PromptText(UserEntry(new JsonArray(Entry.Text("a"), Entry.Text("b")))));
        Assert.Null(Transcripts.Transcripts.PromptText(UserEntry(new JsonArray(Entry.ToolResult("t", "out")))));
        Assert.Null(Transcripts.Transcripts.PromptText(new JsonObject { ["type"] = "assistant", ["message"] = new JsonObject { ["content"] = "x" } }));
    }

    [Fact]
    public void ToolSummaries()
    {
        string S(string name, JsonObject input) => Transcripts.Transcripts.Summary(name, input);
        Assert.Equal("ls -la", S("Bash", new JsonObject { ["command"] = "ls -la" }));
        Assert.Equal("List files", S("Bash", new JsonObject { ["command"] = "ls -la", ["description"] = "List files" }));
        Assert.Equal("c.swift", S("Edit", new JsonObject { ["file_path"] = "/a/b/c.swift", ["old_string"] = "x" }));
        Assert.Equal("App.cs", S("Write", new JsonObject { ["file_path"] = @"C:\src\App.cs" }));
        Assert.Equal("TODO", S("Grep", new JsonObject { ["pattern"] = "TODO" }));
        Assert.Equal("할 일 목록 갱신", S("TodoWrite", new JsonObject { ["todos"] = new JsonArray() }));
        Assert.Equal("a", S("mcp__x__y", new JsonObject { ["zeta"] = "z", ["alpha"] = "a" }));
        Assert.Equal("https://e.com", S("mcp__x__y", new JsonObject { ["zeta"] = "z", ["url"] = "https://e.com" }));
        Assert.Equal("", S("Unknown", new JsonObject()));
    }

    [Fact]
    public void ResultText()
    {
        Assert.Equal("a b", Transcripts.Transcripts.ResultText("a\n\nb"));
        Assert.Equal("one two", Transcripts.Transcripts.ResultText(new JsonArray(
            new JsonObject { ["type"] = "text", ["text"] = "one" }, new JsonObject { ["type"] = "image" }, new JsonObject { ["type"] = "text", ["text"] = "two" })));
        Assert.Null(Transcripts.Transcripts.ResultText(null));
    }
}
